apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-{{.Values.namespace}}
  namespace: {{.Values.namespace}}
spec:
  rules:
    - http:
        paths:
          {{- range $microSvc,$config := .Values.pathConfig}}
          {{- range $path := $config.paths}}
          - path: {{$path}}
            pathType: Prefix
            backend:
              service:
                name: {{$config.service}}
                port:
                  number: {{$config.port}}
          {{- end}}
          {{- end}}
