/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tutorial.app;

//import tutorial.list.LinkedList;

import static tutorial.utilities.StringUtils.join;
import static tutorial.utilities.StringUtils.split;
import static tutorial.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
//        LinkedList tokens;
//        tokens = split(getMessage());
//        String result = join(tokens);
//        System.out.println(WordUtils.capitalize(result));
    }
}
